// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// assignAgePen
NumericVector assignAgePen(NumericVector ageInt, NumericVector AgeDiagIndex, IntegerVector status);
RcppExport SEXP _ccLRforR_assignAgePen(SEXP ageIntSEXP, SEXP AgeDiagIndexSEXP, SEXP statusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ageInt(ageIntSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AgeDiagIndex(AgeDiagIndexSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type status(statusSEXP);
    rcpp_result_gen = Rcpp::wrap(assignAgePen(ageInt, AgeDiagIndex, status));
    return rcpp_result_gen;
END_RCPP
}
// calculateLikelihood
NumericVector calculateLikelihood(NumericVector S0, NumericVector S1, NumericVector RR, IntegerVector status);
RcppExport SEXP _ccLRforR_calculateLikelihood(SEXP S0SEXP, SEXP S1SEXP, SEXP RRSEXP, SEXP statusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type RR(RRSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type status(statusSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateLikelihood(S0, S1, RR, status));
    return rcpp_result_gen;
END_RCPP
}
// calculateStatistics
NumericVector calculateStatistics(NumericVector ages);
RcppExport SEXP _ccLRforR_calculateStatistics(SEXP agesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ages(agesSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateStatistics(ages));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ccLRforR_assignAgePen", (DL_FUNC) &_ccLRforR_assignAgePen, 3},
    {"_ccLRforR_calculateLikelihood", (DL_FUNC) &_ccLRforR_calculateLikelihood, 4},
    {"_ccLRforR_calculateStatistics", (DL_FUNC) &_ccLRforR_calculateStatistics, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ccLRforR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
