# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assignAgePen <- function(ageInt, AgeDiagIndex, status) {
    .Call(`_ccLRforR_assignAgePen`, ageInt, AgeDiagIndex, status)
}

calculateLikelihood <- function(S0, S1, RR, status) {
    .Call(`_ccLRforR_calculateLikelihood`, S0, S1, RR, status)
}

calculateStatistics <- function(ages) {
    .Call(`_ccLRforR_calculateStatistics`, ages)
}

